### ISSUE TITLE
[Proof Of Concept] JSX/TSX Support

### ISSUE THREAD

**Issue by only-cliches** [localvoid/ivi#13]
I went to write something like this library just a few weeks ago, love that I found it instead!

I'd really like to see TSX support to make the library a little bit more intuitive for people use to the react way of doing things.

It would be cool to see a new submodule, something like "ivi-jsx" that handles the transition but makes it easy to exclude if people would prefer not to use it.

I threw together this quick proof of concept file:

```ts
import * as ivi from "ivi";
import * as html from "ivi-html";

export interface ElementProps {
  className?: string;
  style?: ivi.HTMLStyleElementAttrs;
  children: ivi.OpNode<ivi.ElementData<any>>[] | ivi.OpNode<ivi.ElementData<any>>
}

export function createElement<Props extends ElementProps>(name:string|((props: Props) => ivi.OpNode<any>), props?: Props, ...children: ivi.OpNode<ivi.ElementData<Props>>[]): ivi.OpNode<ivi.ElementData<Props>> {
    if (typeof name === "string") {
      if (!html[name]) {
        throw new Error(`HTML element "${name}" not found!`);
      }
      const thisProps = props || {} as Props;
      const thisClass = thisProps["className"];
      delete thisProps.className;
      return html[name](thisClass || ivi._, thisProps, children || ivi._);
    } else {
      props.children = children;
      return name(props);
    }
}

export function createComponent<Props, State>(render: (state: ivi.OpState<ivi.ComponentHooks<State>>) => (props: Props) => ivi.OpNode<ivi.ElementData<Props>> | ivi.OpNode<ivi.ElementData<Props>>[]) {
  return ivi.component(render);
}

export function TrackByKey<T>(props: {items: T[], render: (item: T) => [any, ivi.OpNode|ivi.OpNode[]]}) {
  return ivi.TrackByKey(props.items.map(p => {
    const [key, element] = props.render(p);
    return ivi.key(key, element);
  }));
}
```

In addition to the file above, you'll need to drop this into the tsconfig:
```json
        "jsxFactory": "createElement",
        "jsx": "react",
```

Now the blog example:

```jsx
import { createComponent, createElement, TrackByKey } from "ivi-jsx";
import * as ivi from "ivi";

const Blog = createComponent((c) => {
  return (props: {posts: any[]}) => {
    return [
      <TrackByKey items={props.posts} render={(post) => {
        return [post.id, <h2>{post.title}</h2>]
      }} />,
      <hr />,
      <TrackByKey items={props.posts} render={(post) => {
        return [post.id, [<h3>{post.title}</h3>, <p>{post.content}</p>]]
      }} />
    ];
  }
});

const posts = [
  { id: 1, title: "Hello World", content: "Welcome to learning ivi!" },
  { id: 2, title: "Installation", content: "You can install ivi from npm." }
];

ivi.render(<Blog posts={posts} />, document.getElementById("app")!);
```

So far the only weird part I can see is the components must have their children passed down inside the props.  So you'd have to either adjust the library internals or do components like this:

```jsx
const Container = createComponent((c) => {
    return (props) => {
        return <div className="test">{props.children}</div>
    }
});

ivi.render(<Container>Hello<Container/>, document.getElementById("app")!);

// kicks out: <div class="test">Hello</div>
```

I haven't dug super deep into the implications of doing things like this, the prototype I hacked together "seems" to work but I'd really like to get your input on things.

I'd be more than happy to put together a more thought out PR if this looks like a good direction.

**Comment by localvoid** [comment]
Here are some JSX/TSX issues related to ivi implementation:

#### It would require to implement custom JSX/TSX transformer 

`createElement(name, props, ...children)` will be inefficient, it won't be able to support ivi custom elements, ivi element prototypes. React team also wants to ditch this `createElement()` API in favor of something better.

#### ivi components support all value types as props

By default, ivi is using strict equality check as `shouldUpdate` function and in many use cases it will be able to efficiently prevent unnecessary updates without writing any additional code. With jsx, props are wrapped into additional object.

#### ivi composition model supports immediately invoked functions

ivi doesn't have any magic properties (`ref`, `key`, etc) on "virtual dom" nodes to make it possible to use simple immediately invoked functions instead of stateful components in many use cases. With jsx, immediately invoked functions doesn't look right.

**Comment by only-cliches** [comment]
**It would require to implement custom JSX/TSX transformer**
Wouldn't adding additional conditions to the `createElement` function handle this?

**ivi components support all value types as props**
Packaging something like [fast-deep-equal](https://www.npmjs.com/package/fast-deep-equal) and using that as the default `shouldComponentUpdate` for jsx elements would handle this use case.  It's definitely not as streamlined or efficient as the default strict comparison and also adds more bloat.

**ivi composition model supports immediately invoked functions**
I don't think it's critical that 100% React feature compatibility is implemented.  Kind of like you already don't have a `useRef` or `useState` implemented, side stepping some of the features that don't make sense for the library would be fine.

However, it feels like to put this together proper we're going to have to make too many concessions that don't really align with the goals of `ivi` as you've built it so far.

Probably a better idea for this to be an external, unofficial addon than something internal to the lib.  

Thanks for the quick response and awesome library!

**Comment by localvoid** [comment]
> Wouldn't adding additional conditions to the `createElement` function handle this?

The problem is that default jsx transformer converts basic lowercase elements to strings and because of it there are some issues:

- It is impossible to distinguish between html and svg elements (html and svg are using the same tag names for different elements, for example `<a>` element). Many libraries are solving it by tracking svg context when they enter into `<svg>` element.
- SSR implementations require additional tagName checks to detect void and newline-eating elements.

To solve this issues I've decided to use factory functions that encode all this information when factory function is instantiated instead of making all this checks each time in the reconciler/ssr renderer. It also makes API future proof, because I can always add new flags to factory functions and implement efficient workarounds for different edge cases.

`createElement()` implementation on top of factory functions won't be able to distinguish between html and svg elements because it doesn't know in which context it is executed. Also, it would require to import all factory functions even when they aren't used in the application (ivi API is designed with tree-shaking in mind).

**Comment by only-cliches** [comment]
SVG elements can be manually filtered by the user, have some consistent flag in the jsx that signifies it's a SVG element and not an HTML one, like `x_`.  So something like `<x_a />` would get you the svg `a` element and `<x_svg />` would get you the base SVG element.

Then `createElement` could just have a separate case for elements that start with `x_`.

There's no solution to the tree-shaking problem you mentioned (and a few others), I would argue that many people (myself included) would trade a few features and efficiencies for being able to use JSX.

**Comment by localvoid** [comment]
Even if we can fix html/svg issue with some special prefix like `<svg.a>`, there are also custom elements  and element prototypes `elementProto()`, so it won't be able to interop with ivi libraries that weren't written with JSX in mind.

Custom Elements:

```js
// ivi-google-map.js
// export const googleMap = htmlElementFactory("google-map");

import { googleMap } from "ivi-google-map";
render(googleMap(), container);
```

Element Prototypes:

```js
// ivi-checkbox.js
// export const checkbox = elementProto(input(_, { type: "checkbox" }));

import { checkbox } from "ivi-checkbox"; 
render(checkbox("class-name"), container);
```

But I think that this issues are possible to solve with custom JSX/TSX transformer and there are many other libraries that using custom JSX/TSX transformers, so I don't think that this issues are relevant for JSX, it just requires a different JSX transformer.

What I think will be hard to do is creating interop workarounds for components that doesn't use `{}` as props, for example:

```js
const Link = component(
  () => ([text, href]) => a("link", { href }, text),
  shallowNotEqualArray, // shouldComponentUpdate
);
```

Such components will be impossible to consume from JSX without creating wrappers that will convert `{ text, href }` into `[text, href]`.

> I would argue that many people (myself included) would trade a few features and efficiencies for being able to use JSX.

I understand that, and I completely agree. If my primary goal with this library were to gain attention from the community, I could just create an efficient library with React API.

But from my point of view, JSX just adds too much unnecessary constraints and limits composition model. Also, because many component APIs doesn't look ergonomic with JSX, we can often see some crazy stuff like:

```jsx
<Table data={data}>
  <Table.Column id="name" />
  <Table.Column id="fname" />
</Table>
```

**Comment by only-cliches** [comment]
Thanks Boris, appreciate the clarifications.  Seems like JSX support is definitely outside the scope of what you want the library to be doing.
