### ISSUE TITLE
Is there any optimizations about vdom.type?

### ISSUE THREAD

**Issue by yisar** [localvoid/ivi#25]
```js
if (oldVdom.type !== newVdom.type){ // here
  mount(newVdom)
  unmount(oldVdom)
}else{
 diff(oldVdom, newVdom)
}
```
The names of variables are so strange that I can't find them.

**Comment by easafe** [comment]
Take a look at the reconciler, e.g., https://github.com/localvoid/ivi/blob/master/packages/ivi/src/vdom/reconciler.ts#L395

**Comment by yisar** [comment]
@easafe 
I did not find it, but I would like to discuss separately whether it is feasible without this optimization

**Comment by localvoid** [comment]
@yisar You are probably looking at some really old code, or even at the code from some other project. Here is this check in the current codebase: https://github.com/localvoid/ivi/blob/686a8bc13dd1bcc891d5b896fcaf750feec26254/packages/ivi/src/vdom/reconciler.ts#L434-L442

This code checks if new node has a similar type to the previous node, if it matches then it will update and preserve internal state, otherwise it should destroy(unmount) and instantiate(mount) a new internal state. It is not an optimization, it is required for correctness.

I think that `vdom.type` is just a reference to component constructor or a string (tag name).

**Comment by yisar** [comment]
@localvoid Yes, you are right. I didn't find these lines. Thank you～
