### ISSUE TITLE
Possible bug in VNode Class (children method)

### ISSUE THREAD

**Issue by Enrainn** [localvoid/ivi#3]
The method is declared without body ([L194](https://github.com/ivijs/ivi/blob/2c81ead934b9128e092cc2a5ef2d3cabc73cb5dd/packages/ivi/src/vdom/vnode.ts#L194)) then declared again with body but without the parameter types:
([L195](https://github.com/ivijs/ivi/blob/2c81ead934b9128e092cc2a5ef2d3cabc73cb5dd/packages/ivi/src/vdom/vnode.ts#L195)).
In addition, the JSDoc annotation used by the Closure Compiler is bound to the bodiless method and not compiled to JS. 
This may be the cause of Closure Compiler not being able to rename 'children' calls.

**Comment by localvoid** [comment]
It is a workaround to get rid of the code that is generated by typescript compiler, this code converts `arguments` into an array with the name `children`.

I think that Closure Compiler doesn't rename `children` calls because somewhere in the code it can't infer type of an object with a `children` property, so it just stops renaming `children` everywhere to make sure that it won't break anything.  `className` property has a similar behavior, closure compiler just doesn't rename it.

**Comment by Enrainn** [comment]
Understood. Thank you for the explanation.
