### ISSUE TITLE
stopDirtyChecking

### ISSUE THREAD

**Issue by fopsdev** [localvoid/ivi#5]
hi there

i've just discovered ivi and i have a somewhat basic question:
i'm creating custom-elements and the data and changehandling of that data which gets rendered is handled by the custom-element (v1) itself.
does it mean i should always use the ```stopDirtChecking``` as found here:
```js
const Row = statelessComponent(({ id, label, selected }) => (
  stopDirtyChecking(
    tr(selected ? "danger" : "").c(
      td("col-md-1").c(id),
      td("col-md-4").c(a().c(label)),
      td("col-md-1").c(a().c(GlyphIcon("glyphicon glyphicon-remove delete"))),
      td("col-md-6"),
    ),
  )
));
```
or is there a way to globally disable it?
thanks for any enlightment

**Comment by fopsdev** [comment]
aaah wait i see.

if my custom element looks like this:

```js
export class StateC extends OvlHTMLElement {

    getHtml(state) {
        return 
      tr(selected ? "danger" : "").c(
      td("col-md-1").c(id),
      td("col-md-4").c(a().c(label)),
      td("col-md-1").c(a().c(GlyphIcon("glyphicon glyphicon-remove delete"))),
      td("col-md-6"),
    )
    
    }
}
```
then in my baseclass i could implement smth like:
```js
...
...
const Result = statelessComponent(({ id, label, selected }) => (
  stopDirtyChecking(this.getHtml(id, label, selected)})
...
...
```

**Comment by localvoid** [comment]
Hi,

In general, you shouldn't worry about `stopDirtyChecking()`. I've used it in the benchmark because it has ~80k DOM nodes. The only real use case when it makes sense to use `stopDirtyChecking()` is when you render thousands of svg nodes in some svg chart.

But if you don't use contexts/connectors, then dirty checking is completely useless for you, and there is no way to disable it globally. Maybe for your use case it makes sense to fork ivi and remove everything except basic virtual dom.

Also, ivi doesn't work nicely with custom elements. It is possible to use custom elements, and I don't see any problems with it, but rendering internal tree of a custom element with ivi may have some unpredictable results. For example, global `render()` function that renders virtual node into a DOM container is using linear algorithm to find previous virtual node associated with DOM container, synthetic events probably will have problems with shadow dom.

**Comment by fopsdev** [comment]
Hi,

Thanks a lot for the pointers. I will elaborate
